/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProjectsRouteImport } from './routes/projects'
import { Route as StartAProjectRouteImport } from './routes/start-a-project'
import { Route as WorkRoyalBbqRouteImport } from './routes/work.royal-bbq'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsRoute = ProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => rootRouteImport,
} as any)
const StartAProjectRoute = StartAProjectRouteImport.update({
  id: '/start-a-project',
  path: '/start-a-project',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkRoyalBbqRoute = WorkRoyalBbqRouteImport.update({
  id: '/work/royal-bbq',
  path: '/work/royal-bbq',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/projects': typeof ProjectsRoute
  '/start-a-project': typeof StartAProjectRoute
  '/work/royal-bbq': typeof WorkRoyalBbqRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/projects': typeof ProjectsRoute
  '/start-a-project': typeof StartAProjectRoute
  '/work/royal-bbq': typeof WorkRoyalBbqRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/projects': typeof ProjectsRoute
  '/start-a-project': typeof StartAProjectRoute
  '/work/royal-bbq': typeof WorkRoyalBbqRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/projects' | '/start-a-project' | '/work/royal-bbq'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/projects' | '/start-a-project' | '/work/royal-bbq'
  id: '__root__' | '/' | '/projects' | '/start-a-project' | '/work/royal-bbq'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ProjectsRoute: typeof ProjectsRoute
  StartAProjectRoute: typeof StartAProjectRoute
  WorkRoyalBbqRoute: typeof WorkRoyalBbqRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects': {
      id: '/projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof ProjectsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/start-a-project': {
      id: '/start-a-project'
      path: '/start-a-project'
      fullPath: '/start-a-project'
      preLoaderRoute: typeof StartAProjectRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/work/royal-bbq': {
      id: '/work/royal-bbq'
      path: '/work/royal-bbq'
      fullPath: '/work/royal-bbq'
      preLoaderRoute: typeof WorkRoyalBbqRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ProjectsRoute: ProjectsRoute,
  StartAProjectRoute: StartAProjectRoute,
  WorkRoyalBbqRoute: WorkRoyalBbqRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
